### ISSUE TITLE
docker_clone_volume.sh misses dot files in root

### ISSUE THREAD

**Issue by anorm** [gdiepen/docker-convenience-scripts#3]
The `cp -a /from/* .` command does not pick up dot files (like `.bashrc`). Eiter `cp -a /from/* /from/.* .` or using `rsync` would fix the problem.

**Comment by gdiepen** [comment]
Thanks for this!

I just updated the source

**Comment by ghost** [comment]
For me the fix don't work. I get errors

If i change it to `cd /from ; cp -a . /to`. it works fine.
Maybe you can add `-v`: `cd /from ; cp -av . /to`

@gdiepen Please reopen this issue
